-- H2 does not support partial unique indexes (WHERE clause).
-- The application layer enforces this constraint.
-- Production uses: CREATE UNIQUE INDEX ... ON workflow_shipments (passport_id) WHERE status = 'RELEASED';
