-- H2 does not support partial unique indexes (WHERE clause).
-- The application layer enforces this constraint.
-- Production uses: CREATE UNIQUE INDEX ... ON workflow_service_requests (passport_id) WHERE status IN ('PENDING', 'ACCEPTED');
