package io.attestry.userauth.common.error;

public enum ErrorCode {
    DUPLICATE_EMAIL,
    DUPLICATE_ORGANIZATION_NAME,
    DUPLICATE_BIZ_REG_NO,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    USER_SUSPENDED,
    GROUP_NOT_FOUND,
    MEMBERSHIP_NOT_FOUND,
    APPLICATION_NOT_FOUND,
    EVIDENCE_NOT_FOUND,
    EVIDENCE_FILE_LIMIT_EXCEEDED,
    EVIDENCE_FILE_TYPE_NOT_ALLOWED,
    INVALID_APPLICATION_STATE,
    INVITATION_NOT_FOUND,
    ACCESS_TOKEN_INVALID,
    TENANT_ISOLATION_VIOLATION,
    FORBIDDEN_SCOPE
}
