package io.attestry.userauth.common.error;

public enum ErrorCode {
    DUPLICATE_EMAIL,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    USER_SUSPENDED,
    MEMBERSHIP_NOT_FOUND,
    APPLICATION_NOT_FOUND,
    INVALID_APPLICATION_STATE,
    INVITATION_NOT_FOUND,
    ACCESS_TOKEN_INVALID,
    TENANT_ISOLATION_VIOLATION,
    FORBIDDEN_SCOPE
}
