package io.attestry.userauth.domain.auth.model;

public enum Scope {
    PLATFORM_ADMIN,
    TENANT_CREATE_APPROVE,
    TENANT_SUSPEND,
    GLOBAL_AUDIT_READ,
    TENANT_ADMIN,
    BRAND_MINT,
    BRAND_VOID,
    RETAIL_RELEASE,
    RETAIL_TRANSFER_CREATE,
    PASSPORT_PERMISSION_GRANT,
    MEMBERSHIP_MANAGE,
    TENANT_AUDIT_READ,
    OWNER_TRANSFER_CREATE,
    OWNER_TRANSFER_ACCEPT,
    OWNER_RISK_FLAG,
    OWNER_RISK_CLEAR
}
