package io.attestry.workflow.domain;

public enum WorkflowErrorCode {
    DELEGATION_NOT_FOUND,
    DELEGATION_ALREADY_ACTIVE,
    DELEGATION_INVALID_STATE,
    PARTNER_LINK_NOT_FOUND,
    PARTNER_LINK_ALREADY_ACTIVE,
    PARTNER_LINK_INVALID_STATE,
    EVIDENCE_NOT_FOUND,
    INVALID_REQUEST,
    INVALID_STATE,
    TENANT_ISOLATION_VIOLATION,
    FORBIDDEN_SCOPE,
    TRANSFER_NOT_FOUND,
    TRANSFER_INVALID_STATE,
    TRANSFER_EXPIRED,
    TRANSFER_BRUTE_FORCE_BLOCKED,
    TRANSFER_NONCE_MISMATCH,
    TRANSFER_CODE_MISMATCH,
    TRANSFER_ALREADY_PENDING,
    CLAIM_NOT_FOUND,
    CLAIM_INVALID_STATE,
    CLAIM_EVIDENCE_INSUFFICIENT,
    SERVICE_REQUEST_NOT_FOUND,
    SERVICE_REQUEST_INVALID_STATE,
    SERVICE_REQUEST_ALREADY_SUBMITTED
}
