### =========================================================
### User Auth API - Onboarding Scenario Collection
### =========================================================

@baseUrl = http://localhost:8080
@contentType = application/json
@accessToken = 307594e5-ac1b-4fd1-a039-dce1b9eddd3f
@pdfPath = ./user-auth-module/http/files/biz-proof-1.pdf
@pdfSizeBytes = 102400

@tenantId = REPLACE_TENANT_ID
@applicationId = 38d9d8e0-e0b9-42fe-b862-de78b668ca09
@evidenceBundleId = f03548df-83f1-4e08-b4f9-c91acf1b7add





### NOTE
### 현재 도메인 정책은 증빙 파일을 PDF만 허용합니다.
### (image/png, image/jpeg 업로드는 presign 단계/도메인 검증에서 거절됨)

### =========================================================
### A) 원샷 플로우: presign -> upload(PUT) -> complete
### =========================================================


### 4) Create brand application
POST {{baseUrl}}/brand-applications
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "brandName": "GUCCI",
  "country": "KR",
  "bizRegNo": "110-11-56382",
  "evidenceBundleId": "9eb97ab5-a738-4b76-9ab5-07ef768a1249"
}


### 5) Get brand application
GET {{baseUrl}}/brand-applications/{{applicationId}}
Authorization: Bearer {{accessToken}}

