### User Auth - Me APIs

@baseUrl = http://localhost:8080
@accessToken = eb4ad12f-ecc1-4090-bc31-45bf1b75e334

### 1) My memberships
GET {{baseUrl}}/me/memberships
Authorization: Bearer {{accessToken}}
