### User Auth - Me APIs

@baseUrl = http://localhost:8080
@accessToken =  82e2567e-8bba-4802-a037-98c9e36aa2fa

### 1) My account
GET {{baseUrl}}/me/account
Authorization: Bearer {{accessToken}}

### 2) Update my account
PATCH {{baseUrl}}/me/account
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "phone": "",
  "currentPassword": "",
  "newPassword": ""
}

### 3) My memberships
GET {{baseUrl}}/me/memberships
Authorization: Bearer {{accessToken}}
