### User Auth - Onboarding User APIs

@baseUrl = http://localhost:8080
@contentType = application/json
@accessToken = cea0c053-87f7-4128-9eec-69424470bfdd
@applicationId = 7958e5c5-66c5-4b81-997a-05ecbb12b159
@evidenceBundleId = 2f5e8328-b5e9-4034-8f90-f9be78c1de0a
@evidenceFileId = e0b70bea-9c43-4bba-a260-40838fb7fa36
@uploadUrl = http://localhost:9000/attestry-onboarding/onboarding/b377e007-a19b-4412-b6b6-9167c6737d72/2f5e8328-b5e9-4034-8f90-f9be78c1de0a/d91e6691-426c-4e3c-8a93-0469b38cffe4/biz-proof-1.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20260305%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260305T203823Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=3d02ddda11f71f275158fa2a3ebb829d53891f9bfb5266d7188ec6119650bead

### 1) Presign evidence upload
# @name presignEvidence
POST {{baseUrl}}/onboarding/evidences/presign
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "evidenceBundleId": null,
  "fileName": "biz-proof-1.pdf",
  "contentType": "application/pdf"
}

> {%
  client.global.set("evidenceBundleId", response.body.evidenceBundleId);
  client.global.set("evidenceFileId", response.body.evidenceFileId);
  client.global.set("uploadUrl", response.body.uploadUrl);
%}

### 2) Upload file to presigned URL
PUT {{uploadUrl}}
Content-Type: application/pdf

< ./files/biz-proof-1.pdf

### 3) Complete evidence upload
POST {{baseUrl}}/onboarding/evidences/complete
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "evidenceBundleId": "{{evidenceBundleId}}",
  "evidenceFileId": "{{evidenceFileId}}",
  "sizeBytes": 102400
}

### 4) Create onboarding application
POST {{baseUrl}}/onboarding/applications
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "type": "BRAND",
  "orgName": "My Brand Inc.",
  "country": "KR",
  "bizRegNo": "123-45-67890",
  "evidenceBundleId": "{{evidenceBundleId}}"
}

### 5) List my onboarding applications
GET {{baseUrl}}/onboarding/applications
Authorization: Bearer {{accessToken}}

### 6) Get my onboarding application detail
GET {{baseUrl}}/onboarding/applications/{{applicationId}}
Authorization: Bearer {{accessToken}}
