@baseUrl = http://localhost:8080
@contentType = application/json
@accessToken = a6723cb6-1268-4a0b-95b1-49e8cead64d9
@pdfPath = ./user-auth-module/http/files/biz-proof-1.pdf
@pdfSizeBytes = 102400

@tenantId = REPLACE_TENANT_ID
@applicationId = 7724b85e-173a-49aa-a732-ba4052c2205b
@evidenceBundleId = ccef62ca-b1ea-44e4-823f-784b9e87f8e1





### 9) Create retail application (독립 retail tenant 온보딩 신청)
POST {{baseUrl}}/retail-applications
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "retailName": "Attestry Retail Shop",
  "country": "KR",
  "bizRegNo": "220-22-23456",
  "evidenceBundleId": "{{evidenceBundleId}}"
}


### 10) Get retail application
GET {{baseUrl}}/retail-applications/{{applicationId}}
Authorization: Bearer {{accessToken}}

